api:
  dashboard: true
  insecure: true          # habilita dashboard sem autenticação

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    exposedByDefault: false   # só expõe serviços com label traefik.enable=true
